/**
 * `@deviltea/widget-core` public contract.
 *
 * The normative semantic contract is GitHub issue #10 ("Widget composition core architecture —
 * canonical decision log"); its consolidated implementation handoff plus the accepted amendments are
 * authoritative over any comment in this package.
 */

export type {
	AnyDepExpression,
	DependencyBuilder,
	DependencyConsumer,
	EmptyRegisteredDeps,
	MaybeOptional,
	MethodInvokeDepExpression,
	OptionalizableDependencyTarget,
	PropertyGetDepExpression,
	RegisteredDeps,
	SelfDependencyTarget,
	SelfMethodDependencyOperations,
	SelfPropertyDependencyOperations,
	SelfStateDependencyOperations,
	StateGetDepExpression,
	StateSetDepExpression,
	ToExecutedDep,
	ToExecutedDeps,
	UnknownTargetDependencyOperations,
	UnknownTargetStateDependencyOperations,
} from './dep'

export type {
	ExecutionResult,
	FailedExecutionResult,
	SuccessfulExecutionResult,
} from './execution-result'

export type {
	BlueprintCompileView,
	BlueprintNodeConfigFields,
	BlueprintSemanticSlots,
	BlueprintSemanticSlotsView,
	BlueprintWidgetNode,
	BlueprintWidgetNodeBase,
	BlueprintWidgetNodeView,
	CreateWidgetSystemRuntimeOptions,
	InvalidWidgetSystemBlueprint,
	RawWidgetDefinition,
	RawWidgetDefinitionFor,
	ResolvedBlueprintWidgetNode,
	ResolvedBlueprintWidgetNodeFor,
	ResolvedBlueprintWidgetNodeView,
	ResolvedBlueprintWidgetNodeViewFor,
	RuntimeMethod,
	RuntimeMethodSurface,
	RuntimeProperty,
	RuntimePropertySurface,
	RuntimeState,
	RuntimeStateSurface,
	RuntimeWidget,
	RuntimeWidgetFor,
	SelfBlueprintWidgetNode,
	SelfBlueprintWidgetNodeView,
	UnresolvedBlueprintWidgetNode,
	ValidBlueprintView,
	ValidWidgetSystemBlueprint,
	WidgetLocation,
	WidgetLocationView,
	WidgetSystemBlueprint,
	WidgetSystemBlueprintStatus,
	WidgetSystemRuntime,
} from './internal/contract'

export { EMPTY_ISSUES, WidgetSystemRuntimeDisposedError } from './issue'

export type {
	BlueprintConfigIssueSource,
	BlueprintDefinitionIssueSource,
	BlueprintDependencyIssueLocation,
	BlueprintDependencyIssueSource,
	BlueprintDependencyMember,
	BlueprintDependencyOperation,
	BlueprintDependencyReference,
	BlueprintDependencyTarget,
	BlueprintIssue,
	BlueprintIssueLocation,
	BlueprintIssueSource,
	BlueprintMethodIssueLocation,
	BlueprintNodeIssue,
	BlueprintPropertyIssueLocation,
	BlueprintSlotChildIssueLocation,
	BlueprintSlotIssueLocation,
	BlueprintStructureIssueLocation,
	BlueprintStructureIssueSource,
	BlueprintWidgetIssueLocation,
	Issue,
	IssueCollector,
	IssuePath,
	RelativePluginStructureIssueInput,
	RelativeSlotStructureIssueInput,
	RelativeStructureIssueLocation,
	RelativeSystemStructureIssueInput,
	RelativeValueIssueInput,
	RuntimeIssueLocation,
	RuntimeLevelIssue,
	RuntimeMethodArgsIssueSource,
	RuntimeMethodDependencyIssue,
	RuntimeMethodDependencyIssueSource,
	RuntimeMethodIssue,
	RuntimeMethodResultIssueSource,
	RuntimePropertyDependencyIssue,
	RuntimePropertyDependencyIssueSource,
	RuntimePropertyIssue,
	RuntimePropertyResultIssueSource,
	RuntimeStateIssue,
	RuntimeStateOverrideIssueSource,
	RuntimeStateValidationIssueSource,
	WidgetSystemRuntimeIssue,
} from './issue'

export { createWidgetPlugin } from './plugin'

export type {
	AnyWidgetPlugin,
	AnyWidgetPluginTuple,
	WidgetConfigDefinition,
	WidgetConfigValidateContext,
	WidgetInterfacesOf,
	WidgetInterfacesViolation,
	WidgetMethodDefinition,
	WidgetMethodExecuteContext,
	WidgetMethodsSection,
	WidgetMethodValidateArgsContext,
	WidgetPlugin,
	WidgetPluginConfigPhase,
	WidgetPluginDonePhase,
	WidgetPluginInterfacesPhase,
	WidgetPluginMethodsPhase,
	WidgetPluginPropertiesPhase,
	WidgetPluginSlotsPhase,
	WidgetPluginStatePhase,
	WidgetPluginTypeOf,
	WidgetPluginValidateStructure,
	WidgetPluginValidateStructureContext,
	WidgetPropertiesSection,
	WidgetPropertyComputeContext,
	WidgetPropertyDefinition,
	WidgetRegisterDepsContext,
	WidgetResolvedConfigContext,
	WidgetSlotDefinition,
	WidgetSlotDefinitions,
	WidgetSlotValidateStructureContext,
	WidgetStateDefaultContext,
	WidgetStateMemberDefinition,
	WidgetStateSection,
	WidgetStateValidateContext,
} from './plugin'

export { createWidgetSystem } from './system'

export type {
	CreateWidgetSystemOptions,
	WidgetPluginOf,
	WidgetSystem,
	WidgetSystemValidateStructure,
	WidgetSystemValidateStructureContext,
} from './system'

export type {
	HasWidgetCapability,
	NonEmptyReadonlyArray,
	WidgetCapabilityOf,
	WidgetId,
	WidgetInterfaces,
	WidgetInterfacesViolationOf,
	WidgetMemberKey,
	WidgetMemberKeysOf,
	WidgetMemberValueOf,
	WidgetMethodArgsOf,
	WidgetMethodKeyOf,
	WidgetMethodOf,
	WidgetMethodReturnOf,
	WidgetMethodsOf,
	WidgetPropertiesOf,
	WidgetPropertyKeyOf,
	WidgetPropertyValueOf,
	WidgetRawConfigOf,
	WidgetResolvedConfigOf,
	WidgetSlotNameOf,
	WidgetStateKeyOf,
	WidgetStateOf,
	WidgetStateValueOf,
} from './types'
