import { expect, test } from './fixtures'

test('Author workspace exposes Core catalog, Structure commands, and synchronized JSON', async ({ page }) => {
	await page.goto('/')

	await page.getByRole('tab', { name: 'Author' })
		.click()
	await page.getByRole('tab', { name: 'Catalog' })
		.click()
	await expect(page.getByTestId('author-catalog-Stack'))
		.toContainText('Sandbox stack widget')

	await page.getByRole('tab', { name: 'Structure' })
		.click()
	await page.getByRole('button', { name: 'title : Text' })
		.click()
	await page.getByLabel('text')
		.fill('edited in Structure')
	await page.getByRole('button', { name: 'Set value' })
		.click()

	await expect(page.getByTestId('document-status'))
		.toContainText('Document r1')
	await expect(page.getByTestId('author-command-outcome'))
		.toContainText('Author command applied')

	await page.getByRole('tab', { name: 'JSON' })
		.click()
	await expect(page.locator('.view-lines'))
		.toContainText('edited in Structure')
})

test('recovery keeps unresolved/raw-slot nodes visible and navigates node diagnostics through Document focus', async ({ page }) => {
	await page.goto('/')
	await page.locator('select[aria-label="Load a preset"]')
		.selectOption('raw-slot-recovery')
	await expect(page.getByTestId('author-recovery-status'))
		.toContainText('1 unresolved')
	await expect(page.getByTestId('author-recovery-status'))
		.toContainText('1 raw-slot placements')
	await page.getByRole('tab', { name: 'Blueprint' })
		.click()
	await page.getByRole('button', { name: /All diagnostics/ })
		.click()

	await expect(page.getByRole('button', { name: 'mystery-1 : MysteryWidget' }))
		.toBeVisible()
	await expect(page.getByRole('button', { name: 'orphan-1 : Text' }))
		.toBeVisible()
	await expect(page.getByText('sidebar · raw-slot', { exact: true }))
		.toBeVisible()

	const unresolvedDiagnostic = page.locator('[data-testid^="blueprint-diagnostic-"]')
		.filter({ hasText: 'mystery-1 : MysteryWidget' })
		.first()
	await expect(unresolvedDiagnostic)
		.toBeVisible()
	await expect(unresolvedDiagnostic.getByRole('button', { name: 'jump to node' }))
		.toBeVisible()
	const mysteryNode = page.getByRole('button', { name: 'mystery-1 : MysteryWidget' })
	const orphanNode = page.getByRole('button', { name: 'orphan-1 : Text' })
	const mysteryBackgroundBefore = await mysteryNode.evaluate(element => getComputedStyle(element).backgroundColor)
	await unresolvedDiagnostic.getByRole('button', { name: 'jump to node' })
		.click()
	await expect.poll(() => mysteryNode.evaluate(element => getComputedStyle(element).backgroundColor))
		.not.toBe(mysteryBackgroundBefore)
	const mysteryBackgroundAfter = await mysteryNode.evaluate(element => getComputedStyle(element).backgroundColor)
	// `/rgb/` also matches transparent `rgba(...)`; the selected row must have the actual computed
	// surface color and must differ from the unselected recovered sibling.
	expect(mysteryBackgroundAfter)
		.toMatch(/^rgb\(/)
	expect(await orphanNode.evaluate(element => getComputedStyle(element).backgroundColor))
		.not.toBe(mysteryBackgroundAfter)

	await page.getByRole('tab', { name: 'Author' })
		.click()
	const recoveryStatus = page.getByTestId('author-recovery-status')
	await expect(recoveryStatus)
		.toContainText('1 unresolved')
	await expect(recoveryStatus)
		.toContainText('1 raw-slot placements')
})

test('semantic diagnostics navigate to current Document focus while source-only diagnostics remain non-navigable', async ({ page }) => {
	await page.goto('/')
	await page.locator('select[aria-label="Load a preset"]')
		.selectOption('invalid-semantic')
	await page.getByRole('tab', { name: 'Blueprint' })
		.click()
	await page.getByRole('button', { name: /All diagnostics/ })
		.click()

	const semanticDiagnostic = page.locator('[data-testid^="blueprint-diagnostic-"]')
		.filter({ hasText: 'summary-1 : Summary' })
		.first()
	await expect(semanticDiagnostic.getByRole('button', { name: 'jump to node' }))
		.toBeVisible()
	const summaryNode = page.getByRole('button', { name: 'summary-1 : Summary' })
	const counterNode = page.getByRole('button', { name: 'counter-1 : Counter' })
	const summaryBackgroundBefore = await summaryNode.evaluate(element => getComputedStyle(element).backgroundColor)
	await semanticDiagnostic.getByRole('button', { name: 'jump to node' })
		.click()
	await expect.poll(() => summaryNode.evaluate(element => getComputedStyle(element).backgroundColor))
		.not.toBe(summaryBackgroundBefore)
	const summaryBackgroundAfter = await summaryNode.evaluate(element => getComputedStyle(element).backgroundColor)
	// The diagnostic navigation must move the actual Document focus, not merely render a diagnostic
	// whose own transparent background happens to contain the substring "rgb".
	expect(summaryBackgroundAfter)
		.toMatch(/^rgb\(/)
	expect(await counterNode.evaluate(element => getComputedStyle(element).backgroundColor))
		.not.toBe(summaryBackgroundAfter)

	await page.goto('/?lab-test&lang=en')
	await page.waitForFunction(() => typeof (window as any).__WIDGET_LAB_TEST__?.setDraftSourceText === 'function')
	await page.evaluate(() => (window as any).__WIDGET_LAB_TEST__.setDraftSourceText('{'))
	await page.getByRole('button', { name: 'Apply', exact: true })
		.click()
	await expect(page.getByTestId('author-json-draft-status'))
		.toContainText('Syntax error (Lab-only draft)')
	await expect(page.getByTestId('author-source-json-compatibility'))
		.toContainText('Compatible (Core)')
	await expect(page.getByTestId('author-blueprint-status'))
		.toContainText('valid')
})

test('rejects blank numeric Structure values while preserving scalar editing behavior', async ({ page }) => {
	await page.goto('/')
	await page.getByLabel('Switch showcase')
		.selectOption('survey')
	await page.getByRole('tab', { name: 'Author' })
		.click()
	await page.getByRole('tab', { name: 'Structure' })
		.click()
	await page.getByRole('button', { name: 'adults : SurveyNumberQuestion' })
		.click()

	const defaultField = page.getByLabel('default')
	await defaultField.fill('   ')
	await defaultField.locator('..')
		.getByRole('button', { name: 'Set value' })
		.click()
	await expect(page.getByTestId('author-command-outcome'))
		.toContainText('Enter a valid value of the same scalar type.')

	await defaultField.fill('3')
	await defaultField.locator('..')
		.getByRole('button', { name: 'Set value' })
		.click()
	await expect(page.getByTestId('author-command-outcome'))
		.toContainText('Author command applied')
})
